name: random_pick
description: "랜덤픽 - 룰렛, 사다리타기, 팀나누기를 한 번에. PLAY YOUR NEXT WORLD."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#6750E5"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F7F5FC"
  image: assets/icon/splash_logo.png
  android_12:
    color: "#F7F5FC"
    image: assets/icon/splash_logo.png
